[2025-10-20 23:53:52,023: INFO: main: Welcome to our custom logging]
[2025-10-22 08:24:20,411: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:24:20,444: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:24:20,446: INFO: common: created directory at: artifacts]
[2025-10-22 08:24:20,447: INFO: 1950418334: Starting data download...]
[2025-10-22 08:24:20,449: INFO: 1950418334: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:24:22,430: ERROR: 3179086842: An error occurred: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\SamsumData.zip']
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_13196\3179086842.py", line 6, in <module>
    zip_filepath = data_ingestion.download_data()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_13196\1950418334.py", line 11, in download_data
    request.urlretrieve(self.config.source_URL, zip_filepath)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\urllib\request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\SamsumData.zip'
[2025-10-22 08:28:11,872: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:28:11,876: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:28:11,877: INFO: common: created directory at: artifacts]
[2025-10-22 08:28:11,877: INFO: 1950418334: Starting data download...]
[2025-10-22 08:28:11,879: INFO: 1950418334: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:28:45,635: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:28:45,637: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:28:45,638: INFO: common: created directory at: artifacts]
[2025-10-22 08:28:45,638: INFO: 1950418334: Starting data download...]
[2025-10-22 08:28:45,640: INFO: 1950418334: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:28:45,893: ERROR: 3665016634: An error occurred: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\SamsumData.zip']
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_13196\3665016634.py", line 6, in <module>
    zip_file_path = data_ingestion.download_data()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_13196\1950418334.py", line 11, in download_data
    request.urlretrieve(self.config.source_URL, zip_filepath)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\urllib\request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\SamsumData.zip'
[2025-10-22 08:30:39,553: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:30:39,554: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:30:39,556: INFO: common: created directory at: artifacts]
[2025-10-22 08:30:39,558: INFO: 1950418334: Starting data download...]
[2025-10-22 08:30:39,558: INFO: 1950418334: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:30:42,423: ERROR: 3665016634: An error occurred: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\SamsumData.zip']
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_13196\3665016634.py", line 6, in <module>
    zip_file_path = data_ingestion.download_data()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_13196\1950418334.py", line 11, in download_data
    request.urlretrieve(self.config.source_URL, zip_filepath)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\urllib\request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\SamsumData.zip'
[2025-10-22 08:34:46,980: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:34:46,982: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:34:46,984: INFO: common: created directory at: artifacts]
[2025-10-22 08:34:46,985: INFO: 1134313400: Starting data download...]
[2025-10-22 08:34:46,986: INFO: 1134313400: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:34:48,173: INFO: 1134313400: Data download complete.]
[2025-10-22 08:34:48,175: INFO: 1134313400: Extracting data from artifacts\data_ingestion\SamsumData.zip to artifacts\data_ingestion...]
[2025-10-22 08:34:48,176: INFO: 1134313400: Extraction completed.]
[2025-10-22 08:53:37,870: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 08:53:37,873: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:53:37,875: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:53:37,876: INFO: common: created directory at: artifacts]
[2025-10-22 08:53:37,876: INFO: data_ingestion: Starting data download...]
[2025-10-22 08:53:37,877: INFO: data_ingestion: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:53:39,413: INFO: data_ingestion: Data download complete.]
[2025-10-22 08:53:39,413: ERROR: main: Error in stage Data Ingestion Stage: DataIngestion.extract_zip() missing 1 required positional argument: 'zip_file_path']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 8, in <module>
    data_ingestion_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.extract_zip()
TypeError: DataIngestion.extract_zip() missing 1 required positional argument: 'zip_file_path'
[2025-10-22 08:55:40,511: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 08:55:40,512: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:55:40,513: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:55:40,513: INFO: common: created directory at: artifacts]
[2025-10-22 08:55:40,514: INFO: data_ingestion: Starting data download...]
[2025-10-22 08:55:40,514: INFO: data_ingestion: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:55:41,215: INFO: data_ingestion: Data download complete.]
[2025-10-22 08:55:41,215: ERROR: main: Error in stage Data Ingestion Stage: DataIngestion.extract_zip() missing 1 required positional argument: 'zip_file_path']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 8, in <module>
    data_ingestion_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.extract_zip()
TypeError: DataIngestion.extract_zip() missing 1 required positional argument: 'zip_file_path'
[2025-10-22 08:57:51,335: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 08:57:51,336: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:57:51,337: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:57:51,338: INFO: common: created directory at: artifacts]
[2025-10-22 08:57:51,338: INFO: data_ingestion: Starting data download...]
[2025-10-22 08:57:51,338: INFO: data_ingestion: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:57:52,372: INFO: data_ingestion: Data download complete.]
[2025-10-22 08:57:52,372: INFO: data_ingestion: Extracting data from artifacts\data_ingestion\SamsumData.zip to artifacts\data_ingestion...]
[2025-10-22 08:57:52,372: INFO: data_ingestion: Extraction completed.]
[2025-10-22 08:57:52,377: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 16:27:50,104: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 16:27:50,139: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 16:27:50,140: INFO: common: created directory at: artifacts]
[2025-10-22 16:27:50,142: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 16:27:51,331: INFO: 1969300191: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-22 16:27:51,332: INFO: 1969300191: Size of downloaded file: ~ 0 KB]
[2025-10-22 16:27:51,333: INFO: 1969300191: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 16:42:29,077: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 16:42:29,078: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 16:42:29,080: INFO: common: created directory at: artifacts]
[2025-10-22 16:42:29,081: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 16:42:29,083: INFO: 1583535059: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 16:42:29,085: INFO: 1583535059: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 16:49:03,793: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 16:49:03,795: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 16:49:03,795: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 16:49:03,796: INFO: common: created directory at: artifacts]
[2025-10-22 16:49:03,797: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 16:49:05,653: INFO: data_ingestion: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-22 16:49:05,654: INFO: data_ingestion: Size of downloaded file: ~ 0 KB]
[2025-10-22 16:49:05,655: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 16:49:05,656: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 18:52:34,751: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 18:52:34,754: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 18:52:34,756: INFO: common: created directory at: artifacts]
[2025-10-22 18:52:34,758: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:11:02,391: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 19:11:02,393: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:11:02,394: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:11:02,395: INFO: common: created directory at: artifacts]
[2025-10-22 19:11:02,395: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 19:11:03,782: INFO: data_ingestion: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-22 19:11:03,782: INFO: data_ingestion: Size of downloaded file: ~ 0 KB]
[2025-10-22 19:11:03,783: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 19:11:03,783: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 19:11:03,783: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-22 19:11:03,785: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:11:03,786: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:11:03,786: INFO: common: created directory at: artifacts]
[2025-10-22 19:11:03,787: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:11:03,787: ERROR: main: Error in stage Data validation Stage: 'DataValidation' object has no attribute 'download_file']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 21, in <module>
    data_validation_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_02_data_validation.py", line 15, in main
    data_validation.download_file()
AttributeError: 'DataValidation' object has no attribute 'download_file'
[2025-10-22 19:12:32,987: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 19:12:32,989: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:12:32,990: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:12:32,990: INFO: common: created directory at: artifacts]
[2025-10-22 19:12:32,990: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 19:12:32,991: INFO: data_ingestion: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 19:12:32,991: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 19:12:32,991: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 19:12:32,992: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-22 19:12:32,993: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:12:32,993: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:12:32,994: INFO: common: created directory at: artifacts]
[2025-10-22 19:12:32,994: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:12:32,994: ERROR: data_validation: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:12:32,995: ERROR: main: Error in stage Data validation Stage: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 21, in <module>
    data_validation_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_02_data_validation.py", line 17, in main
    status = data_validation.validate_all_files_exist()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 29, in validate_all_files_exist
    raise e
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:13:04,360: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 19:13:04,361: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:13:04,362: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:13:04,363: INFO: common: created directory at: artifacts]
[2025-10-22 19:13:04,363: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 19:13:05,042: INFO: data_ingestion: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-22 19:13:05,043: INFO: data_ingestion: Size of downloaded file: ~ 0 KB]
[2025-10-22 19:13:05,043: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 19:13:05,043: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 19:13:05,044: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-22 19:13:05,045: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:13:05,046: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:13:05,046: INFO: common: created directory at: artifacts]
[2025-10-22 19:13:05,047: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:13:05,047: ERROR: data_validation: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:13:05,047: ERROR: main: Error in stage Data validation Stage: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 21, in <module>
    data_validation_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_02_data_validation.py", line 17, in main
    status = data_validation.validate_all_files_exist()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 29, in validate_all_files_exist
    raise e
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:15:04,938: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 19:15:04,939: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:15:04,940: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:15:04,941: INFO: common: created directory at: artifacts]
[2025-10-22 19:15:04,941: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 19:15:05,605: INFO: data_ingestion: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-22 19:15:05,605: INFO: data_ingestion: Size of downloaded file: ~ 0 KB]
[2025-10-22 19:15:05,606: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 19:15:05,606: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 19:15:05,606: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-22 19:15:05,607: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:15:05,608: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:15:05,608: INFO: common: created directory at: artifacts]
[2025-10-22 19:15:05,608: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:15:05,609: ERROR: data_validation: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:15:05,609: ERROR: main: Error in stage Data validation Stage: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 21, in <module>
    data_validation_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_02_data_validation.py", line 17, in main
    status = data_validation.validate_all_files_exist()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 29, in validate_all_files_exist
    raise e
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:21:20,685: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 19:21:20,686: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:21:20,686: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:21:20,687: INFO: common: created directory at: artifacts]
[2025-10-22 19:21:20,687: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 19:21:21,963: INFO: data_ingestion: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-22 19:21:21,963: INFO: data_ingestion: Size of downloaded file: ~ 0 KB]
[2025-10-22 19:21:21,964: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 19:21:21,964: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 19:21:21,964: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-22 19:21:21,966: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:21:21,966: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:21:21,966: INFO: common: created directory at: artifacts]
[2025-10-22 19:21:21,967: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:21:21,967: ERROR: data_validation: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:21:21,967: ERROR: main: Error in stage Data validation Stage: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 21, in <module>
    data_validation_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_02_data_validation.py", line 17, in main
    status = data_validation.validate_all_files_exist()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 29, in validate_all_files_exist
    raise e
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:22:10,336: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 19:22:10,338: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:22:10,339: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:22:10,339: INFO: common: created directory at: artifacts]
[2025-10-22 19:22:10,339: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 19:22:10,340: INFO: data_ingestion: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 19:22:10,340: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 19:22:10,341: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 19:22:10,341: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-22 19:22:10,342: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:22:10,343: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:22:10,346: INFO: common: created directory at: artifacts]
[2025-10-22 19:22:10,346: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:22:10,347: ERROR: data_validation: [WinError 267] The directory name is invalid: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
NotADirectoryError: [WinError 267] The directory name is invalid: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:22:10,347: ERROR: main: Error in stage Data validation Stage: [WinError 267] The directory name is invalid: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 21, in <module>
    data_validation_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_02_data_validation.py", line 17, in main
    status = data_validation.validate_all_files_exist()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 29, in validate_all_files_exist
    raise e
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
NotADirectoryError: [WinError 267] The directory name is invalid: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:23:03,233: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 19:23:03,235: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:23:03,235: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:23:03,236: INFO: common: created directory at: artifacts]
[2025-10-22 19:23:03,236: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 19:23:03,236: INFO: data_ingestion: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 19:23:03,237: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 19:23:03,237: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 19:23:03,237: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-22 19:23:03,238: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:23:03,239: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:23:03,239: INFO: common: created directory at: artifacts]
[2025-10-22 19:23:03,239: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:23:03,239: INFO: main: >>>>>> Stage Data validation Stage completed <<<<<<

x==========x]
