[2025-10-20 23:53:52,023: INFO: main: Welcome to our custom logging]
[2025-10-22 08:24:20,411: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:24:20,444: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:24:20,446: INFO: common: created directory at: artifacts]
[2025-10-22 08:24:20,447: INFO: 1950418334: Starting data download...]
[2025-10-22 08:24:20,449: INFO: 1950418334: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:24:22,430: ERROR: 3179086842: An error occurred: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\SamsumData.zip']
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_13196\3179086842.py", line 6, in <module>
    zip_filepath = data_ingestion.download_data()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_13196\1950418334.py", line 11, in download_data
    request.urlretrieve(self.config.source_URL, zip_filepath)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\urllib\request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\SamsumData.zip'
[2025-10-22 08:28:11,872: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:28:11,876: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:28:11,877: INFO: common: created directory at: artifacts]
[2025-10-22 08:28:11,877: INFO: 1950418334: Starting data download...]
[2025-10-22 08:28:11,879: INFO: 1950418334: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:28:45,635: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:28:45,637: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:28:45,638: INFO: common: created directory at: artifacts]
[2025-10-22 08:28:45,638: INFO: 1950418334: Starting data download...]
[2025-10-22 08:28:45,640: INFO: 1950418334: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:28:45,893: ERROR: 3665016634: An error occurred: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\SamsumData.zip']
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_13196\3665016634.py", line 6, in <module>
    zip_file_path = data_ingestion.download_data()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_13196\1950418334.py", line 11, in download_data
    request.urlretrieve(self.config.source_URL, zip_filepath)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\urllib\request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\SamsumData.zip'
[2025-10-22 08:30:39,553: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:30:39,554: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:30:39,556: INFO: common: created directory at: artifacts]
[2025-10-22 08:30:39,558: INFO: 1950418334: Starting data download...]
[2025-10-22 08:30:39,558: INFO: 1950418334: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:30:42,423: ERROR: 3665016634: An error occurred: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\SamsumData.zip']
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_13196\3665016634.py", line 6, in <module>
    zip_file_path = data_ingestion.download_data()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_13196\1950418334.py", line 11, in download_data
    request.urlretrieve(self.config.source_URL, zip_filepath)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\urllib\request.py", line 251, in urlretrieve
    tfp = open(filename, 'wb')
FileNotFoundError: [Errno 2] No such file or directory: 'artifacts\\data_ingestion\\SamsumData.zip'
[2025-10-22 08:34:46,980: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:34:46,982: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:34:46,984: INFO: common: created directory at: artifacts]
[2025-10-22 08:34:46,985: INFO: 1134313400: Starting data download...]
[2025-10-22 08:34:46,986: INFO: 1134313400: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:34:48,173: INFO: 1134313400: Data download complete.]
[2025-10-22 08:34:48,175: INFO: 1134313400: Extracting data from artifacts\data_ingestion\SamsumData.zip to artifacts\data_ingestion...]
[2025-10-22 08:34:48,176: INFO: 1134313400: Extraction completed.]
[2025-10-22 08:53:37,870: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 08:53:37,873: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:53:37,875: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:53:37,876: INFO: common: created directory at: artifacts]
[2025-10-22 08:53:37,876: INFO: data_ingestion: Starting data download...]
[2025-10-22 08:53:37,877: INFO: data_ingestion: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:53:39,413: INFO: data_ingestion: Data download complete.]
[2025-10-22 08:53:39,413: ERROR: main: Error in stage Data Ingestion Stage: DataIngestion.extract_zip() missing 1 required positional argument: 'zip_file_path']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 8, in <module>
    data_ingestion_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.extract_zip()
TypeError: DataIngestion.extract_zip() missing 1 required positional argument: 'zip_file_path'
[2025-10-22 08:55:40,511: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 08:55:40,512: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:55:40,513: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:55:40,513: INFO: common: created directory at: artifacts]
[2025-10-22 08:55:40,514: INFO: data_ingestion: Starting data download...]
[2025-10-22 08:55:40,514: INFO: data_ingestion: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:55:41,215: INFO: data_ingestion: Data download complete.]
[2025-10-22 08:55:41,215: ERROR: main: Error in stage Data Ingestion Stage: DataIngestion.extract_zip() missing 1 required positional argument: 'zip_file_path']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 8, in <module>
    data_ingestion_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 16, in main
    data_ingestion.extract_zip()
TypeError: DataIngestion.extract_zip() missing 1 required positional argument: 'zip_file_path'
[2025-10-22 08:57:51,335: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 08:57:51,336: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 08:57:51,337: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 08:57:51,338: INFO: common: created directory at: artifacts]
[2025-10-22 08:57:51,338: INFO: data_ingestion: Starting data download...]
[2025-10-22 08:57:51,338: INFO: data_ingestion: Downloading data from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip to artifacts\data_ingestion\SamsumData.zip...]
[2025-10-22 08:57:52,372: INFO: data_ingestion: Data download complete.]
[2025-10-22 08:57:52,372: INFO: data_ingestion: Extracting data from artifacts\data_ingestion\SamsumData.zip to artifacts\data_ingestion...]
[2025-10-22 08:57:52,372: INFO: data_ingestion: Extraction completed.]
[2025-10-22 08:57:52,377: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 16:27:50,104: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 16:27:50,139: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 16:27:50,140: INFO: common: created directory at: artifacts]
[2025-10-22 16:27:50,142: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 16:27:51,331: INFO: 1969300191: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-22 16:27:51,332: INFO: 1969300191: Size of downloaded file: ~ 0 KB]
[2025-10-22 16:27:51,333: INFO: 1969300191: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 16:42:29,077: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 16:42:29,078: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 16:42:29,080: INFO: common: created directory at: artifacts]
[2025-10-22 16:42:29,081: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 16:42:29,083: INFO: 1583535059: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 16:42:29,085: INFO: 1583535059: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 16:49:03,793: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 16:49:03,795: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 16:49:03,795: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 16:49:03,796: INFO: common: created directory at: artifacts]
[2025-10-22 16:49:03,797: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 16:49:05,653: INFO: data_ingestion: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-22 16:49:05,654: INFO: data_ingestion: Size of downloaded file: ~ 0 KB]
[2025-10-22 16:49:05,655: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 16:49:05,656: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 18:52:34,751: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 18:52:34,754: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 18:52:34,756: INFO: common: created directory at: artifacts]
[2025-10-22 18:52:34,758: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:11:02,391: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 19:11:02,393: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:11:02,394: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:11:02,395: INFO: common: created directory at: artifacts]
[2025-10-22 19:11:02,395: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 19:11:03,782: INFO: data_ingestion: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-22 19:11:03,782: INFO: data_ingestion: Size of downloaded file: ~ 0 KB]
[2025-10-22 19:11:03,783: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 19:11:03,783: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 19:11:03,783: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-22 19:11:03,785: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:11:03,786: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:11:03,786: INFO: common: created directory at: artifacts]
[2025-10-22 19:11:03,787: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:11:03,787: ERROR: main: Error in stage Data validation Stage: 'DataValidation' object has no attribute 'download_file']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 21, in <module>
    data_validation_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_02_data_validation.py", line 15, in main
    data_validation.download_file()
AttributeError: 'DataValidation' object has no attribute 'download_file'
[2025-10-22 19:12:32,987: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 19:12:32,989: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:12:32,990: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:12:32,990: INFO: common: created directory at: artifacts]
[2025-10-22 19:12:32,990: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 19:12:32,991: INFO: data_ingestion: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 19:12:32,991: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 19:12:32,991: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 19:12:32,992: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-22 19:12:32,993: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:12:32,993: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:12:32,994: INFO: common: created directory at: artifacts]
[2025-10-22 19:12:32,994: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:12:32,994: ERROR: data_validation: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:12:32,995: ERROR: main: Error in stage Data validation Stage: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 21, in <module>
    data_validation_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_02_data_validation.py", line 17, in main
    status = data_validation.validate_all_files_exist()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 29, in validate_all_files_exist
    raise e
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:13:04,360: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 19:13:04,361: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:13:04,362: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:13:04,363: INFO: common: created directory at: artifacts]
[2025-10-22 19:13:04,363: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 19:13:05,042: INFO: data_ingestion: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-22 19:13:05,043: INFO: data_ingestion: Size of downloaded file: ~ 0 KB]
[2025-10-22 19:13:05,043: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 19:13:05,043: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 19:13:05,044: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-22 19:13:05,045: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:13:05,046: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:13:05,046: INFO: common: created directory at: artifacts]
[2025-10-22 19:13:05,047: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:13:05,047: ERROR: data_validation: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:13:05,047: ERROR: main: Error in stage Data validation Stage: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 21, in <module>
    data_validation_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_02_data_validation.py", line 17, in main
    status = data_validation.validate_all_files_exist()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 29, in validate_all_files_exist
    raise e
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:15:04,938: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 19:15:04,939: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:15:04,940: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:15:04,941: INFO: common: created directory at: artifacts]
[2025-10-22 19:15:04,941: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 19:15:05,605: INFO: data_ingestion: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-22 19:15:05,605: INFO: data_ingestion: Size of downloaded file: ~ 0 KB]
[2025-10-22 19:15:05,606: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 19:15:05,606: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 19:15:05,606: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-22 19:15:05,607: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:15:05,608: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:15:05,608: INFO: common: created directory at: artifacts]
[2025-10-22 19:15:05,608: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:15:05,609: ERROR: data_validation: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:15:05,609: ERROR: main: Error in stage Data validation Stage: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 21, in <module>
    data_validation_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_02_data_validation.py", line 17, in main
    status = data_validation.validate_all_files_exist()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 29, in validate_all_files_exist
    raise e
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:21:20,685: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 19:21:20,686: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:21:20,686: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:21:20,687: INFO: common: created directory at: artifacts]
[2025-10-22 19:21:20,687: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 19:21:21,963: INFO: data_ingestion: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-22 19:21:21,963: INFO: data_ingestion: Size of downloaded file: ~ 0 KB]
[2025-10-22 19:21:21,964: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 19:21:21,964: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 19:21:21,964: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-22 19:21:21,966: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:21:21,966: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:21:21,966: INFO: common: created directory at: artifacts]
[2025-10-22 19:21:21,967: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:21:21,967: ERROR: data_validation: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:21:21,967: ERROR: main: Error in stage Data validation Stage: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 21, in <module>
    data_validation_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_02_data_validation.py", line 17, in main
    status = data_validation.validate_all_files_exist()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 29, in validate_all_files_exist
    raise e
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:22:10,336: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 19:22:10,338: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:22:10,339: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:22:10,339: INFO: common: created directory at: artifacts]
[2025-10-22 19:22:10,339: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 19:22:10,340: INFO: data_ingestion: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 19:22:10,340: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 19:22:10,341: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 19:22:10,341: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-22 19:22:10,342: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:22:10,343: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:22:10,346: INFO: common: created directory at: artifacts]
[2025-10-22 19:22:10,346: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:22:10,347: ERROR: data_validation: [WinError 267] The directory name is invalid: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
NotADirectoryError: [WinError 267] The directory name is invalid: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:22:10,347: ERROR: main: Error in stage Data validation Stage: [WinError 267] The directory name is invalid: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 21, in <module>
    data_validation_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_02_data_validation.py", line 17, in main
    status = data_validation.validate_all_files_exist()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 29, in validate_all_files_exist
    raise e
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
NotADirectoryError: [WinError 267] The directory name is invalid: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-22 19:23:03,233: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 19:23:03,235: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:23:03,235: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:23:03,236: INFO: common: created directory at: artifacts]
[2025-10-22 19:23:03,236: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 19:23:03,236: INFO: data_ingestion: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 19:23:03,237: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 19:23:03,237: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 19:23:03,237: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-22 19:23:03,238: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:23:03,239: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:23:03,239: INFO: common: created directory at: artifacts]
[2025-10-22 19:23:03,239: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:23:03,239: INFO: main: >>>>>> Stage Data validation Stage completed <<<<<<

x==========x]
[2025-10-22 19:52:20,697: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:52:20,700: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:52:20,702: INFO: common: created directory at: artifacts]
[2025-10-22 19:52:20,705: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-22 19:52:20,706: ERROR: 2383176258: Incorrect path_or_model_id: 'google\pegasus-cnn_dailymail'. Please provide either the path to a local folder or the repo_id of a model on the Hub.]
Traceback (most recent call last):
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\transformers\utils\hub.py", line 402, in cached_file
    resolved_file = hf_hub_download(
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\huggingface_hub\utils\_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'google\pegasus-cnn_dailymail'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_21248\2383176258.py", line 4, in <module>
    data_transformation = DataTransformation(config=data_transformation_config)
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_21248\1537832415.py", line 4, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(self.config.tokenizer_name)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 834, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 666, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\transformers\utils\hub.py", line 466, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'google\pegasus-cnn_dailymail'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
[2025-10-22 19:56:46,150: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 19:56:46,152: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:56:46,153: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:56:46,153: INFO: common: created directory at: artifacts]
[2025-10-22 19:56:46,154: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 19:56:46,154: INFO: data_ingestion: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 19:56:46,155: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 19:56:46,155: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

x==========x]
[2025-10-22 19:56:46,155: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-22 19:56:46,156: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:56:46,157: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:56:46,158: INFO: common: created directory at: artifacts]
[2025-10-22 19:56:46,158: INFO: common: created directory at: artifacts/data_validation]
[2025-10-22 19:56:46,158: INFO: main: >>>>>> Stage Data validation Stage completed <<<<<<

x==========x]
[2025-10-22 19:58:38,063: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 19:58:38,066: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 19:58:38,068: INFO: common: created directory at: artifacts]
[2025-10-22 19:58:38,071: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-22 19:58:38,073: ERROR: 2383176258: Incorrect path_or_model_id: 'google\pegasus-cnn_dailymail'. Please provide either the path to a local folder or the repo_id of a model on the Hub.]
Traceback (most recent call last):
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\transformers\utils\hub.py", line 402, in cached_file
    resolved_file = hf_hub_download(
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\huggingface_hub\utils\_validators.py", line 106, in _inner_fn
    validate_repo_id(arg_value)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\huggingface_hub\utils\_validators.py", line 160, in validate_repo_id
    raise HFValidationError(
huggingface_hub.errors.HFValidationError: Repo id must use alphanumeric chars or '-', '_', '.', '--' and '..' are forbidden, '-' and '.' cannot start or end the name, max length is 96: 'google\pegasus-cnn_dailymail'.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_21248\2383176258.py", line 4, in <module>
    data_transformation = DataTransformation(config=data_transformation_config)
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_21248\1537832415.py", line 4, in __init__
    self.tokenizer = AutoTokenizer.from_pretrained(self.config.tokenizer_name)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 834, in from_pretrained
    tokenizer_config = get_tokenizer_config(pretrained_model_name_or_path, **kwargs)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\transformers\models\auto\tokenization_auto.py", line 666, in get_tokenizer_config
    resolved_config_file = cached_file(
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\transformers\utils\hub.py", line 466, in cached_file
    raise EnvironmentError(
OSError: Incorrect path_or_model_id: 'google\pegasus-cnn_dailymail'. Please provide either the path to a local folder or the repo_id of a model on the Hub.
[2025-10-22 20:04:53,162: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 20:04:53,165: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 20:04:53,167: INFO: common: created directory at: artifacts]
[2025-10-22 20:04:53,169: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-22 20:04:58,587: ERROR: 4090147737: Directory artifacts\data_ingestion\Samsum_dataset is neither a `Dataset` directory nor a `DatasetDict` directory.]
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_21248\4090147737.py", line 5, in <module>
    data_transformation.convert()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_21248\1537832415.py", line 18, in convert
    dataset_samsum = load_from_disk(self.config.data_path)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1479, in load_from_disk
    raise FileNotFoundError(
FileNotFoundError: Directory artifacts\data_ingestion\Samsum_dataset is neither a `Dataset` directory nor a `DatasetDict` directory.
[2025-10-22 20:05:42,075: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 20:05:42,077: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 20:05:42,079: INFO: common: created directory at: artifacts]
[2025-10-22 20:05:42,081: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-22 20:05:42,930: ERROR: 4090147737: Directory artifacts\data_ingestion\samsum_dataset is neither a `Dataset` directory nor a `DatasetDict` directory.]
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_21248\4090147737.py", line 5, in <module>
    data_transformation.convert()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_21248\1537832415.py", line 18, in convert
    dataset_samsum = load_from_disk(self.config.data_path)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1479, in load_from_disk
    raise FileNotFoundError(
FileNotFoundError: Directory artifacts\data_ingestion\samsum_dataset is neither a `Dataset` directory nor a `DatasetDict` directory.
[2025-10-22 20:17:11,442: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 20:17:11,447: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 20:17:11,449: INFO: common: created directory at: artifacts]
[2025-10-22 20:17:11,452: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-22 20:17:13,877: ERROR: 4090147737: Directory artifacts\data_ingestion\samsum_dataset is neither a `Dataset` directory nor a `DatasetDict` directory.]
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_21248\4090147737.py", line 5, in <module>
    data_transformation.convert()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_21248\1537832415.py", line 18, in convert
    dataset_samsum = load_from_disk(self.config.data_path)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1479, in load_from_disk
    raise FileNotFoundError(
FileNotFoundError: Directory artifacts\data_ingestion\samsum_dataset is neither a `Dataset` directory nor a `DatasetDict` directory.
[2025-10-22 20:22:20,828: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 20:22:20,833: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 20:22:20,836: INFO: common: created directory at: artifacts]
[2025-10-22 20:22:20,838: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-22 20:22:22,060: ERROR: 4090147737: Directory artifacts\data_ingestion\samsum_dataset is neither a `Dataset` directory nor a `DatasetDict` directory.]
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_23380\4090147737.py", line 5, in <module>
    data_transformation.convert()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_23380\1467856860.py", line 18, in convert
    samsum_dataset = load_from_disk(self.config.data_path)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1479, in load_from_disk
    raise FileNotFoundError(
FileNotFoundError: Directory artifacts\data_ingestion\samsum_dataset is neither a `Dataset` directory nor a `DatasetDict` directory.
[2025-10-22 21:10:52,316: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 21:10:52,317: ERROR: main: Error in stage Data Ingestion Stage: 'DataIngestionPipeline' object has no attribute 'prepare_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 9, in <module>
    data_ingestion_pipeline.prepare_dataset()
AttributeError: 'DataIngestionPipeline' object has no attribute 'prepare_dataset'
[2025-10-22 21:13:56,991: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 21:13:56,993: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 21:13:56,994: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 21:13:56,994: INFO: common: created directory at: artifacts]
[2025-10-22 21:13:56,995: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 21:13:56,995: INFO: data_ingestion: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 21:13:56,995: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 21:13:56,996: ERROR: main: Error in stage Data Ingestion Stage: 'DataIngestionPipeline' object has no attribute 'data_ingestion']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 9, in <module>
    data_ingestion_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 19, in main
    self.data_ingestion.prepare_dataset()
AttributeError: 'DataIngestionPipeline' object has no attribute 'data_ingestion'
[2025-10-22 21:18:13,628: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 21:18:13,630: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 21:18:13,631: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 21:18:13,632: INFO: common: created directory at: artifacts]
[2025-10-22 21:18:13,632: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 21:18:13,634: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 21:18:13,635: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 21:18:13,635: INFO: common: created directory at: artifacts]
[2025-10-22 21:18:13,636: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 21:18:13,636: INFO: data_ingestion: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 21:18:13,637: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 21:18:14,241: ERROR: main: Error in stage Data Ingestion Stage: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.]
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 9, in <module>
    data_ingestion_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 21, in main
    self.data_ingestion.prepare_dataset()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_ingestion.py", line 33, in prepare_dataset
    dataset = load_dataset("samsum")
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1397, in load_dataset
    builder_instance = load_dataset_builder(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1137, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1030, in dataset_module_factory
    raise e1 from None
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 985, in dataset_module_factory
    raise DatasetNotFoundError(f"Dataset '{path}' doesn't exist on the Hub or cannot be accessed.") from e
datasets.exceptions.DatasetNotFoundError: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.
[2025-10-22 21:36:40,737: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 21:36:40,739: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 21:36:40,740: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 21:36:40,740: INFO: common: created directory at: artifacts]
[2025-10-22 21:36:40,740: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 21:36:40,743: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 21:36:40,743: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 21:36:40,743: INFO: common: created directory at: artifacts]
[2025-10-22 21:36:40,743: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 21:36:42,145: INFO: data_ingestion: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-22 21:36:42,146: INFO: data_ingestion: Size of downloaded file: ~ 0 KB]
[2025-10-22 21:36:42,148: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 21:36:42,706: ERROR: main: Error in stage Data Ingestion Stage: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.]
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 10, in <module>
    dataset =data_ingestion_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 21, in main
    self.data_ingestion.prepare_dataset()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_ingestion.py", line 33, in prepare_dataset
    dataset = load_dataset("samsum")
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1397, in load_dataset
    builder_instance = load_dataset_builder(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1137, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1030, in dataset_module_factory
    raise e1 from None
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 985, in dataset_module_factory
    raise DatasetNotFoundError(f"Dataset '{path}' doesn't exist on the Hub or cannot be accessed.") from e
datasets.exceptions.DatasetNotFoundError: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.
[2025-10-22 21:37:36,987: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 21:37:36,987: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 21:37:36,989: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 21:37:36,989: INFO: common: created directory at: artifacts]
[2025-10-22 21:37:36,989: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 21:37:36,991: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 21:37:36,991: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 21:37:36,992: INFO: common: created directory at: artifacts]
[2025-10-22 21:37:36,992: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 21:37:37,653: INFO: data_ingestion: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-22 21:37:37,654: INFO: data_ingestion: Size of downloaded file: ~ 0 KB]
[2025-10-22 21:37:37,654: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 21:37:38,153: ERROR: main: Error in stage Data Ingestion Stage: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.]
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 10, in <module>
    dataset =data_ingestion_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 21, in main
    self.data_ingestion.prepare_dataset()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_ingestion.py", line 33, in prepare_dataset
    dataset = load_dataset("samsum")
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1397, in load_dataset
    builder_instance = load_dataset_builder(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1137, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1030, in dataset_module_factory
    raise e1 from None
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 985, in dataset_module_factory
    raise DatasetNotFoundError(f"Dataset '{path}' doesn't exist on the Hub or cannot be accessed.") from e
datasets.exceptions.DatasetNotFoundError: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.
[2025-10-22 21:40:12,150: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 21:40:12,154: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 21:40:12,157: INFO: common: created directory at: artifacts]
[2025-10-22 21:40:12,159: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 21:41:45,164: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 21:41:45,166: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 21:41:45,169: INFO: common: created directory at: artifacts]
[2025-10-22 21:41:45,172: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 21:41:45,173: INFO: common: created directory at: artifacts\data_ingestion]
[2025-10-22 21:41:45,175: INFO: 3745921866: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 21:43:42,523: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 21:43:42,527: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 21:43:42,531: INFO: common: created directory at: artifacts]
[2025-10-22 21:43:42,534: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 21:43:42,537: INFO: common: created directory at: artifacts\data_ingestion]
[2025-10-22 21:43:42,539: INFO: 3745921866: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 21:44:04,559: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 21:44:04,561: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 21:44:04,563: INFO: common: created directory at: artifacts]
[2025-10-22 21:44:04,566: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 21:44:04,568: INFO: common: created directory at: artifacts\data_ingestion]
[2025-10-22 21:44:04,569: INFO: 3745921866: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 21:45:00,518: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 21:45:00,522: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 21:45:00,524: INFO: common: created directory at: artifacts]
[2025-10-22 21:45:00,527: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 21:45:00,529: INFO: common: created directory at: artifacts\data_ingestion]
[2025-10-22 21:45:00,530: INFO: 3745921866: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 21:45:00,533: INFO: common: created directory at: artifacts\data_ingestion]
[2025-10-22 21:45:00,535: INFO: 3745921866: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 23:30:13,664: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 23:30:13,666: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 23:30:13,668: INFO: common: created directory at: artifacts]
[2025-10-22 23:30:13,669: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-22 23:30:14,980: ERROR: 4090147737: Directory artifacts\data_ingestion\samsum_dataset not found]
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_20956\4090147737.py", line 5, in <module>
    data_transformation.convert()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_20956\1467856860.py", line 18, in convert
    samsum_dataset = load_from_disk(self.config.data_path)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1471, in load_from_disk
    raise FileNotFoundError(f"Directory {dataset_path} not found")
FileNotFoundError: Directory artifacts\data_ingestion\samsum_dataset not found
[2025-10-22 23:33:22,859: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 23:33:22,861: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 23:33:22,862: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 23:33:22,862: INFO: common: created directory at: artifacts]
[2025-10-22 23:33:22,863: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 23:33:22,864: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 23:33:22,865: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 23:33:22,867: INFO: common: created directory at: artifacts]
[2025-10-22 23:33:22,868: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 23:33:24,248: INFO: data_ingestion: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-22 23:33:24,249: INFO: data_ingestion: Size of downloaded file: ~ 0 KB]
[2025-10-22 23:33:24,251: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 23:33:24,826: ERROR: main: Error in stage Data Ingestion Stage: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.]
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 10, in <module>
    dataset =data_ingestion_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 21, in main
    self.data_ingestion.prepare_dataset()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_ingestion.py", line 33, in prepare_dataset
    dataset = load_dataset("samsum")
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1397, in load_dataset
    builder_instance = load_dataset_builder(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1137, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1030, in dataset_module_factory
    raise e1 from None
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 985, in dataset_module_factory
    raise DatasetNotFoundError(f"Dataset '{path}' doesn't exist on the Hub or cannot be accessed.") from e
datasets.exceptions.DatasetNotFoundError: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.
[2025-10-22 23:37:16,200: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 23:37:16,203: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 23:37:16,204: INFO: common: created directory at: artifacts]
[2025-10-22 23:37:16,205: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 23:37:16,207: INFO: common: created directory at: artifacts\data_ingestion]
[2025-10-22 23:37:16,209: INFO: 3745921866: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 23:37:16,210: INFO: common: created directory at: artifacts\data_ingestion]
[2025-10-22 23:37:16,212: INFO: 3745921866: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 23:42:27,729: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-22 23:42:27,740: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 23:42:27,741: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 23:42:27,742: INFO: common: created directory at: artifacts]
[2025-10-22 23:42:27,742: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 23:42:27,744: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 23:42:27,744: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 23:42:27,745: INFO: common: created directory at: artifacts]
[2025-10-22 23:42:27,745: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 23:42:27,745: INFO: data_ingestion: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 23:42:27,746: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 23:42:28,769: ERROR: main: Error in stage Data Ingestion Stage: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.]
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 10, in <module>
    dataset =data_ingestion_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 21, in main
    self.data_ingestion.prepare_dataset()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_ingestion.py", line 33, in prepare_dataset
    dataset = load_dataset("samsum")
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1397, in load_dataset
    builder_instance = load_dataset_builder(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1137, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1030, in dataset_module_factory
    raise e1 from None
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 985, in dataset_module_factory
    raise DatasetNotFoundError(f"Dataset '{path}' doesn't exist on the Hub or cannot be accessed.") from e
datasets.exceptions.DatasetNotFoundError: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.
[2025-10-22 23:47:49,798: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 23:47:49,801: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 23:47:49,802: INFO: common: created directory at: artifacts]
[2025-10-22 23:47:49,804: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 23:47:49,806: INFO: common: created directory at: artifacts\data_ingestion]
[2025-10-22 23:47:49,809: INFO: 3745921866: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-22 23:47:49,810: INFO: common: created directory at: artifacts\data_ingestion]
[2025-10-22 23:47:49,812: INFO: 3745921866: Extracted zip file to artifacts\data_ingestion]
[2025-10-22 23:57:44,400: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-22 23:57:44,404: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-22 23:57:44,407: INFO: common: created directory at: artifacts]
[2025-10-22 23:57:44,410: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-22 23:57:44,412: INFO: common: created directory at: artifacts\data_ingestion]
[2025-10-22 23:57:44,413: INFO: 3140536359: File already exists at artifacts\data_ingestion\SamsumData.zip]
[2025-10-23 00:00:37,818: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 00:00:37,822: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 00:00:37,823: INFO: common: created directory at: artifacts]
[2025-10-23 00:00:37,826: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 00:00:37,829: INFO: common: created directory at: artifacts\data_ingestion]
[2025-10-23 00:00:38,734: INFO: 3140536359: Downloaded artifacts\data_ingestion\SamsumData.zip from https://github.com/MR-AMINUR/New-Repo/raw/refs/heads/main/SamsumData.zip]
[2025-10-23 00:00:38,736: INFO: 3140536359: Size of downloaded file: ~ 0 KB]
[2025-10-23 00:57:58,711: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 00:57:58,715: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 00:57:58,717: INFO: common: created directory at: artifacts]
[2025-10-23 00:57:58,720: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 00:58:01,813: INFO: 3114257384: File: artifacts/data_ingestion/data.zip downloaded with following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 24CB:37DDB:2C8539:54D4EC:68F93035
Accept-Ranges: bytes
Date: Wed, 22 Oct 2025 19:28:01 GMT
Via: 1.1 varnish
X-Served-By: cache-ccu830027-CCU
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1761161281.922550,VS0,VE732
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 6961395e51cbda439aab24c1a9550dc6fb9184d1
Expires: Wed, 22 Oct 2025 19:33:01 GMT
Source-Age: 0

]
[2025-10-23 00:58:01,918: INFO: 3114257384: File extracted to artifacts/data_ingestion]
[2025-10-23 01:09:23,845: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 01:09:23,847: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 01:09:23,848: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 01:09:23,849: INFO: common: created directory at: artifacts]
[2025-10-23 01:09:23,849: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 01:09:23,851: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 01:09:23,852: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 01:09:23,854: INFO: common: created directory at: artifacts]
[2025-10-23 01:09:23,854: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 01:09:27,051: INFO: data_ingestion: Downloaded artifacts\data_ingestion\data.zip from https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip]
[2025-10-23 01:09:27,053: INFO: data_ingestion: Size of downloaded file: ~ 7718 KB]
[2025-10-23 01:09:27,153: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-23 01:09:27,775: ERROR: main: Error in stage Data Ingestion Stage: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.]
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 10, in <module>
    dataset =data_ingestion_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 21, in main
    self.data_ingestion.prepare_dataset()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_ingestion.py", line 33, in prepare_dataset
    dataset = load_dataset("samsum")
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1397, in load_dataset
    builder_instance = load_dataset_builder(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1137, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1030, in dataset_module_factory
    raise e1 from None
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 985, in dataset_module_factory
    raise DatasetNotFoundError(f"Dataset '{path}' doesn't exist on the Hub or cannot be accessed.") from e
datasets.exceptions.DatasetNotFoundError: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.
[2025-10-23 01:14:37,618: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 01:14:37,621: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 01:14:37,623: INFO: common: created directory at: artifacts]
[2025-10-23 01:14:37,625: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 01:24:06,827: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 01:24:06,829: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 01:24:06,829: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 01:24:06,830: INFO: common: created directory at: artifacts]
[2025-10-23 01:24:06,830: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 01:24:06,831: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 01:24:06,832: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 01:24:06,832: INFO: common: created directory at: artifacts]
[2025-10-23 01:24:06,832: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 01:24:09,997: INFO: data_ingestion: Downloaded artifacts\data_ingestion\data.zip from https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip]
[2025-10-23 01:24:09,998: INFO: data_ingestion: Size of downloaded file: ~ 7718 KB]
[2025-10-23 01:24:10,090: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-23 01:24:10,644: ERROR: main: Error in stage Data Ingestion Stage: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.]
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 10, in <module>
    dataset =data_ingestion_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 21, in main
    self.data_ingestion.prepare_dataset()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_ingestion.py", line 33, in prepare_dataset
    dataset = load_dataset("samsum")
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1397, in load_dataset
    builder_instance = load_dataset_builder(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1137, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1030, in dataset_module_factory
    raise e1 from None
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 985, in dataset_module_factory
    raise DatasetNotFoundError(f"Dataset '{path}' doesn't exist on the Hub or cannot be accessed.") from e
datasets.exceptions.DatasetNotFoundError: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.
[2025-10-23 01:33:06,653: INFO: main: >>>>>> Stage Data validation Stage started <<<<<<]
[2025-10-23 01:33:06,655: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 01:33:06,656: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 01:33:06,657: INFO: common: created directory at: artifacts]
[2025-10-23 01:33:06,657: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 01:33:06,657: ERROR: data_validation: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-23 01:33:06,658: ERROR: main: Error in stage Data validation Stage: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 22, in <module>
    data_validation_pipeline.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_02_data_validation.py", line 17, in main
    data_validation.validate_all_files_exist()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 29, in validate_all_files_exist
    raise e
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_validation.py", line 13, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-23 01:38:35,337: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 01:38:35,340: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 01:38:35,342: INFO: common: created directory at: artifacts]
[2025-10-23 01:38:35,345: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 01:38:35,346: ERROR: 2962765456: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_25416\2962765456.py", line 9, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-23 01:38:35,348: ERROR: 2432114696: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset']
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_25416\2432114696.py", line 7, in <module>
    status = data_validation.validate_all_files_exist()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_25416\2962765456.py", line 25, in validate_all_files_exist
    raise e
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_25416\2962765456.py", line 9, in validate_all_files_exist
    all_files = os.listdir(os.path.join("artifacts","data_ingestion","samsum_dataset"))
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'artifacts\\data_ingestion\\samsum_dataset'
[2025-10-23 01:38:48,802: ERROR: 2432114696: [Errno 2] No such file or directory: 'config\\config.yaml']
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_25416\2432114696.py", line 2, in <module>
    config = ConfigurationManager()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_25416\519435022.py", line 7, in __init__
    self.config = read_yaml(config_filepath)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\ensure\main.py", line 849, in __call__
    return_val = self.f(*args, **kwargs)
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\utils\common.py", line 32, in read_yaml
    raise e
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\utils\common.py", line 21, in read_yaml
    with open(path_to_yaml, 'r') as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'config\\config.yaml'
[2025-10-23 01:39:26,959: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 01:39:26,962: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 01:39:26,965: INFO: common: created directory at: artifacts]
[2025-10-23 01:39:26,966: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 01:39:29,584: INFO: 3114257384: File: artifacts/data_ingestion/data.zip downloaded with following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 24CB:37DDB:2C8539:54D4EC:68F93035
Accept-Ranges: bytes
Date: Wed, 22 Oct 2025 20:09:29 GMT
Via: 1.1 varnish
X-Served-By: cache-ccu830051-CCU
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1761163769.170044,VS0,VE250
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 069e7cd57f0d41fa2dcffe1adc9091a51c5f0c97
Expires: Wed, 22 Oct 2025 20:14:29 GMT
Source-Age: 0

]
[2025-10-23 01:39:29,684: INFO: 3114257384: File extracted to artifacts/data_ingestion]
[2025-10-23 01:41:24,013: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 01:41:24,016: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 01:41:24,018: INFO: common: created directory at: artifacts]
[2025-10-23 01:41:24,021: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 01:51:18,959: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 01:51:18,960: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 01:51:18,962: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 01:51:18,962: INFO: common: created directory at: artifacts]
[2025-10-23 01:51:18,963: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 01:51:18,963: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 01:51:18,964: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 01:51:18,966: INFO: common: created directory at: artifacts]
[2025-10-23 01:51:18,966: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 01:51:21,901: INFO: data_ingestion: Downloaded artifacts\data_ingestion\data.zip from https://github.com/entbappy/Branching-tutorial/raw/master/summarizer-data.zip]
[2025-10-23 01:51:21,901: INFO: data_ingestion: Size of downloaded file: ~ 7718 KB]
[2025-10-23 01:51:21,991: INFO: data_ingestion: Extracted zip file to artifacts\data_ingestion]
[2025-10-23 01:51:22,551: ERROR: main: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.]
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 9, in <module>
    data_ingestion.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_01_data_ingestion.py", line 21, in main
    self.data_ingestion.prepare_dataset()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_ingestion.py", line 33, in prepare_dataset
    dataset = load_dataset("samsum")
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1397, in load_dataset
    builder_instance = load_dataset_builder(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1137, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1030, in dataset_module_factory
    raise e1 from None
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 985, in dataset_module_factory
    raise DatasetNotFoundError(f"Dataset '{path}' doesn't exist on the Hub or cannot be accessed.") from e
datasets.exceptions.DatasetNotFoundError: Dataset 'samsum' doesn't exist on the Hub or cannot be accessed.
[2025-10-23 01:59:06,009: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 01:59:06,010: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 01:59:06,010: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 01:59:06,011: INFO: common: created directory at: artifacts]
[2025-10-23 01:59:06,011: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 01:59:06,012: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 01:59:06,013: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 01:59:06,014: INFO: common: created directory at: artifacts]
[2025-10-23 01:59:06,014: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 01:59:09,018: INFO: data_ingestion: File: artifacts\data_ingestion\data.zip downloaded with following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 24CB:37DDB:2C8539:54D4EC:68F93035
Accept-Ranges: bytes
Date: Wed, 22 Oct 2025 20:29:08 GMT
Via: 1.1 varnish
X-Served-By: cache-ccu830021-CCU
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1761164949.538746,VS0,VE249
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: ca8eb2d7a1c85c75bf4e17f411c076cf845a9d72
Expires: Wed, 22 Oct 2025 20:34:08 GMT
Source-Age: 0

]
[2025-10-23 01:59:09,115: INFO: data_ingestion: File extracted to artifacts\data_ingestion]
[2025-10-23 01:59:09,116: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

X==========x]
[2025-10-23 01:59:09,116: INFO: main: >>>>>> Stage Data Validation Stage started <<<<<<]
[2025-10-23 01:59:09,117: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 01:59:09,118: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 01:59:09,119: INFO: common: created directory at: artifacts]
[2025-10-23 01:59:09,119: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 01:59:09,120: INFO: main: >>>>>> Stage Data Validation Stage completed <<<<<<

X==========x]
[2025-10-23 02:12:46,698: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 02:12:46,701: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 02:12:46,704: INFO: common: created directory at: artifacts]
[2025-10-23 02:12:46,708: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 02:24:32,485: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 02:24:32,486: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 02:24:32,487: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 02:24:32,488: INFO: common: created directory at: artifacts]
[2025-10-23 02:24:32,488: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 02:24:32,489: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 02:24:32,490: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 02:24:32,490: INFO: common: created directory at: artifacts]
[2025-10-23 02:24:32,491: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 02:24:35,363: INFO: data_ingestion: File: artifacts\data_ingestion\data.zip downloaded with following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 24CB:37DDB:2C8539:54D4EC:68F93035
Accept-Ranges: bytes
Date: Wed, 22 Oct 2025 20:54:35 GMT
Via: 1.1 varnish
X-Served-By: cache-ccu830040-CCU
X-Cache: HIT
X-Cache-Hits: 0
X-Timer: S1761166475.156860,VS0,VE265
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 84feb1f26d2a0a8a8bb9d3c175413e318df34e4a
Expires: Wed, 22 Oct 2025 20:59:35 GMT
Source-Age: 0

]
[2025-10-23 02:24:35,454: INFO: data_ingestion: File extracted to artifacts\data_ingestion]
[2025-10-23 02:24:35,455: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

X==========x]
[2025-10-23 02:24:35,455: INFO: main: >>>>>> Stage Data Validation Stage started <<<<<<]
[2025-10-23 02:24:35,457: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 02:24:35,457: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 02:24:35,458: INFO: common: created directory at: artifacts]
[2025-10-23 02:24:35,458: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 02:24:35,459: INFO: main: >>>>>> Stage Data Validation Stage completed <<<<<<

X==========x]
[2025-10-23 02:24:35,459: INFO: main: >>>>>> Stage Data Transformation Stage started <<<<<<]
[2025-10-23 02:24:35,461: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 02:24:35,461: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 02:24:35,462: INFO: common: created directory at: artifacts]
[2025-10-23 02:24:35,462: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 02:24:38,663: INFO: main: >>>>>> Stage Data Transformation Stage completed <<<<<<

X==========x]
[2025-10-23 03:03:42,173: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 03:03:42,176: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 03:03:42,178: INFO: common: created directory at: artifacts]
[2025-10-23 03:17:13,930: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 03:17:13,935: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 03:17:13,937: INFO: common: created directory at: artifacts]
[2025-10-23 03:22:32,996: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 03:22:33,002: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 03:22:33,006: INFO: common: created directory at: artifacts]
[2025-10-23 03:32:59,775: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 03:32:59,778: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 03:32:59,779: INFO: common: created directory at: artifacts]
[2025-10-23 03:35:26,742: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 03:35:26,745: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 03:35:26,747: INFO: common: created directory at: artifacts]
[2025-10-23 08:40:28,495: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 08:40:28,505: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 08:40:28,507: INFO: common: created directory at: artifacts]
[2025-10-23 08:49:29,079: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 08:49:29,081: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 08:49:29,081: INFO: common: created directory at: artifacts]
[2025-10-23 08:49:29,083: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 08:51:35,934: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 08:51:35,937: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 08:51:35,939: INFO: common: created directory at: artifacts]
[2025-10-23 08:51:35,941: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 08:52:27,245: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 08:52:27,248: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 08:52:27,249: INFO: common: created directory at: artifacts]
[2025-10-23 08:52:27,249: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 08:57:28,364: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 08:57:28,367: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 08:57:28,368: INFO: common: created directory at: artifacts]
[2025-10-23 08:57:28,370: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 08:57:31,297: WARNING: file_download: Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`]
[2025-10-23 09:12:27,206: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 09:12:27,209: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:12:27,210: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:12:27,211: INFO: common: created directory at: artifacts]
[2025-10-23 09:12:27,211: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 09:12:27,213: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:12:27,215: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:12:27,215: INFO: common: created directory at: artifacts]
[2025-10-23 09:12:27,216: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 09:12:27,246: INFO: data_ingestion: File already exists of size: ~ 7718 KB]
[2025-10-23 09:12:27,352: INFO: data_ingestion: File extracted to artifacts\data_ingestion]
[2025-10-23 09:12:27,352: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

X==========x]
[2025-10-23 09:12:27,353: INFO: main: >>>>>> Stage Data Validation Stage started <<<<<<]
[2025-10-23 09:12:27,356: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:12:27,358: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:12:27,359: INFO: common: created directory at: artifacts]
[2025-10-23 09:12:27,359: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 09:12:27,361: INFO: main: >>>>>> Stage Data Validation Stage completed <<<<<<

X==========x]
[2025-10-23 09:12:27,361: INFO: main: >>>>>> Stage Data Transformation Stage started <<<<<<]
[2025-10-23 09:12:27,363: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:12:27,364: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:12:27,365: INFO: common: created directory at: artifacts]
[2025-10-23 09:12:27,365: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 09:12:29,030: INFO: main: >>>>>> Stage Data Transformation Stage completed <<<<<<

X==========x]
[2025-10-23 09:12:58,344: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:12:58,347: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:12:58,349: INFO: common: created directory at: artifacts]
[2025-10-23 09:12:58,351: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 09:19:04,370: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:19:04,373: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:19:04,375: INFO: common: created directory at: artifacts]
[2025-10-23 09:19:04,376: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 09:26:30,024: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:26:30,027: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:26:30,029: INFO: common: created directory at: artifacts]
[2025-10-23 09:26:30,031: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 09:28:57,308: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:28:57,311: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:28:57,311: INFO: common: created directory at: artifacts]
[2025-10-23 09:28:57,313: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 09:31:06,606: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 09:31:06,609: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:31:06,611: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:31:06,611: INFO: common: created directory at: artifacts]
[2025-10-23 09:31:06,612: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 09:31:06,614: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:31:06,615: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:31:06,615: INFO: common: created directory at: artifacts]
[2025-10-23 09:31:06,615: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 09:31:06,616: INFO: data_ingestion: File already exists of size: ~ 7718 KB]
[2025-10-23 09:31:06,714: INFO: data_ingestion: File extracted to artifacts\data_ingestion]
[2025-10-23 09:31:06,715: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

X==========x]
[2025-10-23 09:31:06,716: INFO: main: >>>>>> Stage Data Validation Stage started <<<<<<]
[2025-10-23 09:31:06,717: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:31:06,719: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:31:06,719: INFO: common: created directory at: artifacts]
[2025-10-23 09:31:06,719: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 09:31:06,721: INFO: main: >>>>>> Stage Data Validation Stage completed <<<<<<

X==========x]
[2025-10-23 09:31:06,721: INFO: main: >>>>>> Stage Data Transformation Stage started <<<<<<]
[2025-10-23 09:31:06,722: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:31:06,724: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:31:06,724: INFO: common: created directory at: artifacts]
[2025-10-23 09:31:06,725: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 09:31:08,164: ERROR: main: Directory artifacts/data_ingestion/samsum_dataset_pt not found]
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 37, in <module>
    data_transformation.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_03_data_transformation.py", line 15, in main
    data_transformation.convert()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_transformation.py", line 23, in convert
    dataset_samsum = load_from_disk(self.config.data_path)
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1471, in load_from_disk
    raise FileNotFoundError(f"Directory {dataset_path} not found")
FileNotFoundError: Directory artifacts/data_ingestion/samsum_dataset_pt not found
[2025-10-23 09:33:48,269: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 09:33:48,272: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:33:48,274: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:33:48,274: INFO: common: created directory at: artifacts]
[2025-10-23 09:33:48,275: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 09:33:48,277: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:33:48,278: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:33:48,279: INFO: common: created directory at: artifacts]
[2025-10-23 09:33:48,279: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 09:33:48,280: INFO: data_ingestion: File already exists of size: ~ 7718 KB]
[2025-10-23 09:33:48,377: INFO: data_ingestion: File extracted to artifacts\data_ingestion]
[2025-10-23 09:33:48,377: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

X==========x]
[2025-10-23 09:33:48,378: INFO: main: >>>>>> Stage Data Validation Stage started <<<<<<]
[2025-10-23 09:33:48,379: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:33:48,381: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:33:48,381: INFO: common: created directory at: artifacts]
[2025-10-23 09:33:48,382: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 09:33:48,383: INFO: main: >>>>>> Stage Data Validation Stage completed <<<<<<

X==========x]
[2025-10-23 09:33:48,383: INFO: main: >>>>>> Stage Data Transformation Stage started <<<<<<]
[2025-10-23 09:33:48,385: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:33:48,386: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:33:48,387: INFO: common: created directory at: artifacts]
[2025-10-23 09:33:48,387: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 09:33:49,700: ERROR: main: Directory artifacts/data_transformation/dataset_samsum_pt not found]
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 37, in <module>
    data_transformation.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_03_data_transformation.py", line 15, in main
    data_transformation.convert()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_transformation.py", line 23, in convert
    dataset_samsum = load_from_disk(self.config.data_path)
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1471, in load_from_disk
    raise FileNotFoundError(f"Directory {dataset_path} not found")
FileNotFoundError: Directory artifacts/data_transformation/dataset_samsum_pt not found
[2025-10-23 09:38:43,474: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:38:43,477: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:38:43,479: INFO: common: created directory at: artifacts]
[2025-10-23 09:38:43,480: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 09:38:44,865: ERROR: 2218786241: Couldn't find any data file at d:\Version Control\AI-Text-Summarizer\artifacts\data_transformation\dataset_samsum_pt.]
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_19488\2218786241.py", line 5, in <module>
    data_transformation.convert()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_19488\1926586559.py", line 17, in convert
    dataset_samsum = load_dataset(self.config.data_path)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1397, in load_dataset
    builder_instance = load_dataset_builder(
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1137, in load_dataset_builder
    dataset_module = dataset_module_factory(
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1038, in dataset_module_factory
    raise FileNotFoundError(f"Couldn't find any data file at {relative_to_absolute_path(path)}.")
FileNotFoundError: Couldn't find any data file at d:\Version Control\AI-Text-Summarizer\artifacts\data_transformation\dataset_samsum_pt.
[2025-10-23 09:39:33,492: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:39:33,495: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:39:33,497: INFO: common: created directory at: artifacts]
[2025-10-23 09:39:33,498: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 09:39:34,483: ERROR: 2218786241: Directory artifacts/data_transformation/dataset_samsum_pt not found]
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_19488\2218786241.py", line 5, in <module>
    data_transformation.convert()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_19488\2268924124.py", line 17, in convert
    dataset_samsum = load_from_disk(self.config.data_path)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1471, in load_from_disk
    raise FileNotFoundError(f"Directory {dataset_path} not found")
FileNotFoundError: Directory artifacts/data_transformation/dataset_samsum_pt not found
[2025-10-23 09:40:20,988: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:40:20,991: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:40:20,994: INFO: common: created directory at: artifacts]
[2025-10-23 09:40:20,996: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 09:40:21,952: ERROR: 2218786241: Directory artifacts/data_transformation/dataset_samsum not found]
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_19488\2218786241.py", line 5, in <module>
    data_transformation.convert()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_19488\2268924124.py", line 17, in convert
    dataset_samsum = load_from_disk(self.config.data_path)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1471, in load_from_disk
    raise FileNotFoundError(f"Directory {dataset_path} not found")
FileNotFoundError: Directory artifacts/data_transformation/dataset_samsum not found
[2025-10-23 09:41:58,863: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:41:58,866: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:41:58,869: INFO: common: created directory at: artifacts]
[2025-10-23 09:41:58,871: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 09:41:58,873: INFO: 3114257384: File already exists of size: ~ 7718 KB]
[2025-10-23 09:41:58,990: INFO: 3114257384: File extracted to artifacts/data_ingestion]
[2025-10-23 09:43:42,675: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:43:42,678: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:43:42,680: INFO: common: created directory at: artifacts]
[2025-10-23 09:43:42,682: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 09:45:33,798: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 09:45:33,800: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:45:33,801: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:45:33,801: INFO: common: created directory at: artifacts]
[2025-10-23 09:45:33,802: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 09:45:33,805: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:45:33,806: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:45:33,806: INFO: common: created directory at: artifacts]
[2025-10-23 09:45:33,806: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 09:45:33,807: INFO: data_ingestion: File already exists of size: ~ 7718 KB]
[2025-10-23 09:45:33,920: INFO: data_ingestion: File extracted to artifacts\data_ingestion]
[2025-10-23 09:45:33,920: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

X==========x]
[2025-10-23 09:45:33,921: INFO: main: >>>>>> Stage Data Validation Stage started <<<<<<]
[2025-10-23 09:45:33,922: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:45:33,923: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:45:33,924: INFO: common: created directory at: artifacts]
[2025-10-23 09:45:33,924: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 09:45:33,926: INFO: main: >>>>>> Stage Data Validation Stage completed <<<<<<

X==========x]
[2025-10-23 09:46:11,963: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 09:46:11,965: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:46:11,967: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:46:11,967: INFO: common: created directory at: artifacts]
[2025-10-23 09:46:11,967: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 09:46:11,969: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:46:11,970: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:46:11,971: INFO: common: created directory at: artifacts]
[2025-10-23 09:46:11,971: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 09:46:16,191: INFO: data_ingestion: File: artifacts\data_ingestion\data.zip downloaded with following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: F514:148546:346626:68B323:68F9AC0C
Accept-Ranges: bytes
Date: Thu, 23 Oct 2025 04:16:15 GMT
Via: 1.1 varnish
X-Served-By: cache-ccu830029-CCU
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1761192975.545426,VS0,VE748
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 79498869c22c0dd9c16b896b0055269df6b33b25
Expires: Thu, 23 Oct 2025 04:21:15 GMT
Source-Age: 0

]
[2025-10-23 09:46:16,290: INFO: data_ingestion: File extracted to artifacts\data_ingestion]
[2025-10-23 09:46:16,290: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

X==========x]
[2025-10-23 09:46:16,290: INFO: main: >>>>>> Stage Data Validation Stage started <<<<<<]
[2025-10-23 09:46:16,292: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:46:16,294: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:46:16,294: INFO: common: created directory at: artifacts]
[2025-10-23 09:46:16,295: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 09:46:16,296: INFO: main: >>>>>> Stage Data Validation Stage completed <<<<<<

X==========x]
[2025-10-23 09:49:31,092: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:49:31,096: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:49:31,098: INFO: common: created directory at: artifacts]
[2025-10-23 09:49:31,120: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 09:49:32,586: ERROR: 2218786241: Directory artifacts/data_transformation/dataset_samsum not found]
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_15308\2218786241.py", line 5, in <module>
    data_transformation.convert()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_15308\946371063.py", line 17, in convert
    dataset_samsum = load_from_disk(self.config.data_path)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1471, in load_from_disk
    raise FileNotFoundError(f"Directory {dataset_path} not found")
FileNotFoundError: Directory artifacts/data_transformation/dataset_samsum not found
[2025-10-23 09:59:37,007: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 09:59:37,009: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 09:59:37,011: INFO: common: created directory at: artifacts]
[2025-10-23 09:59:37,012: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 09:59:38,558: ERROR: 2218786241: Directory artifacts/data_ingestion/dataset_samsum not found]
Traceback (most recent call last):
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_15308\2218786241.py", line 5, in <module>
    data_transformation.convert()
  File "C:\Users\aminu\AppData\Local\Temp\ipykernel_15308\946371063.py", line 17, in convert
    dataset_samsum = load_from_disk(self.config.data_path)
  File "c:\Users\aminu\miniconda3\envs\textS\lib\site-packages\datasets\load.py", line 1471, in load_from_disk
    raise FileNotFoundError(f"Directory {dataset_path} not found")
FileNotFoundError: Directory artifacts/data_ingestion/dataset_samsum not found
[2025-10-23 10:00:18,234: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 10:00:18,237: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 10:00:18,239: INFO: common: created directory at: artifacts]
[2025-10-23 10:00:18,240: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 10:01:00,995: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 10:01:00,997: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 10:01:00,999: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 10:01:00,999: INFO: common: created directory at: artifacts]
[2025-10-23 10:01:01,000: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 10:01:01,001: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 10:01:01,002: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 10:01:01,003: INFO: common: created directory at: artifacts]
[2025-10-23 10:01:01,003: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 10:01:01,003: INFO: data_ingestion: File already exists of size: ~ 7718 KB]
[2025-10-23 10:01:01,100: INFO: data_ingestion: File extracted to artifacts\data_ingestion]
[2025-10-23 10:01:01,100: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

X==========x]
[2025-10-23 10:01:01,101: INFO: main: >>>>>> Stage Data Validation Stage started <<<<<<]
[2025-10-23 10:01:01,102: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 10:01:01,103: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 10:01:01,104: INFO: common: created directory at: artifacts]
[2025-10-23 10:01:01,104: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 10:01:01,105: INFO: main: >>>>>> Stage Data Validation Stage completed <<<<<<

X==========x]
[2025-10-23 10:01:01,106: INFO: main: >>>>>> Stage Data Transformation Stage started <<<<<<]
[2025-10-23 10:01:01,107: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 10:01:01,109: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 10:01:01,109: INFO: common: created directory at: artifacts]
[2025-10-23 10:01:01,109: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 10:01:04,834: INFO: main: >>>>>> Stage Data Transformation Stage completed <<<<<<

X==========x]
[2025-10-23 10:31:35,023: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 10:31:35,025: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 10:31:35,027: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 10:31:35,027: INFO: common: created directory at: artifacts]
[2025-10-23 10:31:35,027: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 10:31:35,030: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 10:31:35,031: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 10:31:35,031: INFO: common: created directory at: artifacts]
[2025-10-23 10:31:35,032: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 10:31:35,032: INFO: data_ingestion: File already exists of size: ~ 7718 KB]
[2025-10-23 10:31:35,127: INFO: data_ingestion: File extracted to artifacts\data_ingestion]
[2025-10-23 10:31:35,128: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

X==========x]
[2025-10-23 10:31:35,128: INFO: main: >>>>>> Stage Data Validation Stage started <<<<<<]
[2025-10-23 10:31:35,130: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 10:31:35,131: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 10:31:35,132: INFO: common: created directory at: artifacts]
[2025-10-23 10:31:35,133: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 10:31:35,134: INFO: main: >>>>>> Stage Data Validation Stage completed <<<<<<

X==========x]
[2025-10-23 10:31:35,135: INFO: main: >>>>>> Stage Data Transformation Stage started <<<<<<]
[2025-10-23 10:31:35,136: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 10:31:35,138: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 10:31:35,138: INFO: common: created directory at: artifacts]
[2025-10-23 10:31:35,139: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 10:31:36,685: INFO: main: >>>>>> Stage Data Transformation Stage completed <<<<<<

X==========x]
[2025-10-23 10:52:07,690: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 10:52:07,693: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 10:52:07,694: INFO: common: created directory at: artifacts]
[2025-10-23 10:59:45,138: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 10:59:45,141: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 10:59:45,143: INFO: common: created directory at: artifacts]
[2025-10-23 11:10:34,274: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:10:34,277: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:10:34,279: INFO: common: created directory at: artifacts]
[2025-10-23 11:11:04,758: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:11:04,762: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:11:04,764: INFO: common: created directory at: artifacts]
[2025-10-23 11:14:37,719: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:14:37,722: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:14:37,724: INFO: common: created directory at: artifacts]
[2025-10-23 11:19:36,582: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:19:36,586: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:19:36,588: INFO: common: created directory at: artifacts]
[2025-10-23 11:24:14,603: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:24:14,606: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:24:14,608: INFO: common: created directory at: artifacts]
[2025-10-23 11:24:14,609: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 11:26:22,833: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 11:26:22,836: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:26:22,838: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:26:22,838: INFO: common: created directory at: artifacts]
[2025-10-23 11:26:22,839: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 11:26:22,840: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:26:22,842: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:26:22,842: INFO: common: created directory at: artifacts]
[2025-10-23 11:26:22,843: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 11:26:22,843: INFO: data_ingestion: File already exists of size: ~ 7718 KB]
[2025-10-23 11:26:22,941: INFO: data_ingestion: File extracted to artifacts\data_ingestion]
[2025-10-23 11:26:22,941: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

X==========x]
[2025-10-23 11:26:22,941: INFO: main: >>>>>> Stage Data Validation Stage started <<<<<<]
[2025-10-23 11:26:22,943: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:26:22,945: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:26:22,945: INFO: common: created directory at: artifacts]
[2025-10-23 11:26:22,946: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 11:26:22,947: INFO: main: >>>>>> Stage Data Validation Stage completed <<<<<<

X==========x]
[2025-10-23 11:26:22,947: INFO: main: >>>>>> Stage Data Transformation Stage started <<<<<<]
[2025-10-23 11:26:22,948: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:26:22,950: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:26:22,950: INFO: common: created directory at: artifacts]
[2025-10-23 11:26:22,950: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 11:26:24,513: INFO: main: >>>>>> Stage Data Transformation Stage completed <<<<<<

X==========x]
[2025-10-23 11:29:02,727: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:29:02,731: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:29:02,733: INFO: common: created directory at: artifacts]
[2025-10-23 11:30:50,930: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:30:50,933: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:30:50,935: INFO: common: created directory at: artifacts]
[2025-10-23 11:30:50,936: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 11:36:22,420: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:36:22,423: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:36:22,425: INFO: common: created directory at: artifacts]
[2025-10-23 11:36:22,427: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 11:38:54,526: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:38:54,532: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:38:54,536: INFO: common: created directory at: artifacts]
[2025-10-23 11:38:54,539: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 11:39:03,279: WARNING: file_download: Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`]
[2025-10-23 11:42:06,598: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:42:06,601: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:42:06,603: INFO: common: created directory at: artifacts]
[2025-10-23 11:42:06,604: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 11:44:34,343: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:44:34,347: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:44:34,348: INFO: common: created directory at: artifacts]
[2025-10-23 11:44:34,351: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 11:46:17,220: WARNING: file_download: Xet Storage is enabled for this repo, but the 'hf_xet' package is not installed. Falling back to regular HTTP download. For better performance, install the package with: `pip install huggingface_hub[hf_xet]` or `pip install hf_xet`]
[2025-10-23 11:49:06,520: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:49:06,525: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:49:06,528: INFO: common: created directory at: artifacts]
[2025-10-23 11:49:06,529: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 11:54:47,837: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:54:47,839: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:54:47,841: INFO: common: created directory at: artifacts]
[2025-10-23 11:54:47,842: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 11:56:26,017: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:56:26,020: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:56:26,023: INFO: common: created directory at: artifacts]
[2025-10-23 11:56:26,025: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 11:58:51,418: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 11:58:51,423: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 11:58:51,427: INFO: common: created directory at: artifacts]
[2025-10-23 11:58:51,430: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 12:00:13,361: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 12:00:13,368: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 12:00:13,373: INFO: common: created directory at: artifacts]
[2025-10-23 12:00:13,377: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 12:22:38,578: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 12:22:38,588: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 12:22:38,590: INFO: common: created directory at: artifacts]
[2025-10-23 12:22:38,591: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 12:45:52,545: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 12:45:52,548: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 12:45:52,553: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 12:45:52,554: INFO: common: created directory at: artifacts]
[2025-10-23 12:45:52,554: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 12:45:52,556: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 12:45:52,557: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 12:45:52,558: INFO: common: created directory at: artifacts]
[2025-10-23 12:45:52,558: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 12:45:56,146: INFO: data_ingestion: File: artifacts\data_ingestion\data.zip downloaded with following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: C8F0:201C2C:2289C3:41C09F:68F9D61A
Accept-Ranges: bytes
Date: Thu, 23 Oct 2025 07:15:55 GMT
Via: 1.1 varnish
X-Served-By: cache-ccu830042-CCU
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1761203755.985106,VS0,VE782
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 7f5cd40d85cf6d91b57d15878f9c039f0a237760
Expires: Thu, 23 Oct 2025 07:20:55 GMT
Source-Age: 0

]
[2025-10-23 12:45:56,238: INFO: data_ingestion: File extracted to artifacts\data_ingestion]
[2025-10-23 12:45:56,238: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

X==========x]
[2025-10-23 12:45:56,239: INFO: main: >>>>>> Stage Data Validation Stage started <<<<<<]
[2025-10-23 12:45:56,240: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 12:45:56,241: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 12:45:56,242: INFO: common: created directory at: artifacts]
[2025-10-23 12:45:56,242: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 12:45:56,243: INFO: main: >>>>>> Stage Data Validation Stage completed <<<<<<

X==========x]
[2025-10-23 12:45:56,243: INFO: main: >>>>>> Stage Data Transformation Stage started <<<<<<]
[2025-10-23 12:45:56,245: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 12:45:56,246: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 12:45:56,247: INFO: common: created directory at: artifacts]
[2025-10-23 12:45:56,247: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 12:46:00,038: INFO: main: >>>>>> Stage Data Transformation Stage completed <<<<<<

X==========x]
[2025-10-23 12:46:00,038: INFO: main: >>>>>> Stage Model Trainer Stage started <<<<<<]
[2025-10-23 12:46:00,040: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 12:46:00,042: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 12:46:00,042: INFO: common: created directory at: artifacts]
[2025-10-23 12:46:00,043: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 14:50:08,141: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 14:50:08,153: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 14:50:08,157: INFO: common: created directory at: artifacts]
[2025-10-23 14:50:08,159: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 14:58:17,672: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 14:58:17,675: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 14:58:17,678: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 14:58:17,678: INFO: common: created directory at: artifacts]
[2025-10-23 14:58:17,679: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 14:58:17,680: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 14:58:17,681: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 14:58:17,682: INFO: common: created directory at: artifacts]
[2025-10-23 14:58:17,682: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 14:58:21,589: INFO: data_ingestion: File: artifacts\data_ingestion\data.zip downloaded with following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 8B09:2BBA79:3F7992:7ACAED:68F9F533
Accept-Ranges: bytes
Date: Thu, 23 Oct 2025 09:28:21 GMT
Via: 1.1 varnish
X-Served-By: cache-ccu830037-CCU
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1761211700.175041,VS0,VE879
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 901622a56afbc7088f0c9a26f251ab095b6f8ec8
Expires: Thu, 23 Oct 2025 09:33:21 GMT
Source-Age: 0

]
[2025-10-23 14:58:21,682: INFO: data_ingestion: File extracted to artifacts\data_ingestion]
[2025-10-23 14:58:21,682: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

X==========x]
[2025-10-23 14:58:21,683: INFO: main: >>>>>> Stage Data Validation Stage started <<<<<<]
[2025-10-23 14:58:21,685: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 14:58:21,686: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 14:58:21,686: INFO: common: created directory at: artifacts]
[2025-10-23 14:58:21,687: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 14:58:21,687: INFO: main: >>>>>> Stage Data Validation Stage completed <<<<<<

X==========x]
[2025-10-23 14:58:21,688: INFO: main: >>>>>> Stage Data Transformation Stage started <<<<<<]
[2025-10-23 14:58:21,689: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 14:58:21,691: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 14:58:21,691: INFO: common: created directory at: artifacts]
[2025-10-23 14:58:21,691: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 14:58:25,348: INFO: main: >>>>>> Stage Data Transformation Stage completed <<<<<<

X==========x]
[2025-10-23 14:58:25,349: INFO: main: >>>>>> Stage Model Trainer Stage started <<<<<<]
[2025-10-23 14:58:25,350: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 14:58:25,352: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 14:58:25,353: INFO: common: created directory at: artifacts]
[2025-10-23 14:58:25,353: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 17:02:39,269: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 17:02:39,280: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 17:02:39,282: INFO: common: created directory at: artifacts]
[2025-10-23 17:02:39,284: INFO: common: created directory at: artifacts/model_evaluation]
[2025-10-23 17:07:15,642: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 17:07:15,673: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 17:07:15,681: INFO: common: created directory at: artifacts]
[2025-10-23 17:07:15,693: INFO: common: created directory at: artifacts/model_evaluation]
[2025-10-23 17:07:29,791: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 17:07:29,803: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 17:07:29,808: INFO: common: created directory at: artifacts]
[2025-10-23 17:07:29,811: INFO: common: created directory at: artifacts/model_evaluation]
[2025-10-23 17:10:59,529: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 17:10:59,536: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 17:10:59,538: INFO: common: created directory at: artifacts]
[2025-10-23 17:10:59,540: INFO: common: created directory at: artifacts/model_evaluation]
[2025-10-23 17:13:46,532: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 17:13:46,535: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 17:13:46,537: INFO: common: created directory at: artifacts]
[2025-10-23 17:13:46,539: INFO: common: created directory at: artifacts/model_evaluation]
[2025-10-23 18:25:25,134: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 18:25:25,144: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 18:25:25,146: INFO: common: created directory at: artifacts]
[2025-10-23 18:25:25,148: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 18:26:52,805: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 18:26:52,814: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 18:26:52,820: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 18:26:52,821: INFO: common: created directory at: artifacts]
[2025-10-23 18:26:52,821: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 18:26:52,825: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 18:26:52,828: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 18:26:52,829: INFO: common: created directory at: artifacts]
[2025-10-23 18:26:52,829: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 18:26:52,830: INFO: data_ingestion: File already exists of size: ~ 7718 KB]
[2025-10-23 18:26:53,021: INFO: data_ingestion: File extracted to artifacts\data_ingestion]
[2025-10-23 18:26:53,021: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

X==========x]
[2025-10-23 18:26:53,021: INFO: main: >>>>>> Stage Data Validation Stage started <<<<<<]
[2025-10-23 18:26:53,025: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 18:26:53,027: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 18:26:53,028: INFO: common: created directory at: artifacts]
[2025-10-23 18:26:53,028: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 18:26:53,031: INFO: main: >>>>>> Stage Data Validation Stage completed <<<<<<

X==========x]
[2025-10-23 18:26:53,031: INFO: main: >>>>>> Stage Data Transformation Stage started <<<<<<]
[2025-10-23 18:26:53,035: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 18:26:53,037: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 18:26:53,038: INFO: common: created directory at: artifacts]
[2025-10-23 18:26:53,039: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 18:26:55,879: INFO: main: >>>>>> Stage Data Transformation Stage completed <<<<<<

X==========x]
[2025-10-23 18:26:55,880: INFO: main: >>>>>> Stage Model Trainer Stage started <<<<<<]
[2025-10-23 18:26:55,886: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 18:26:55,890: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 18:26:55,891: INFO: common: created directory at: artifacts]
[2025-10-23 18:26:55,892: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 18:29:22,933: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 18:29:22,939: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 18:29:22,941: INFO: common: created directory at: artifacts]
[2025-10-23 18:29:22,942: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 18:37:21,997: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-23 18:37:22,002: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 18:37:22,005: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 18:37:22,005: INFO: common: created directory at: artifacts]
[2025-10-23 18:37:22,006: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 18:37:22,008: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 18:37:22,009: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 18:37:22,009: INFO: common: created directory at: artifacts]
[2025-10-23 18:37:22,010: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-23 18:37:25,509: INFO: data_ingestion: File: artifacts\data_ingestion\data.zip downloaded with following info: 
Connection: close
Content-Length: 7903594
Cache-Control: max-age=300
Content-Security-Policy: default-src 'none'; style-src 'unsafe-inline'; sandbox
Content-Type: application/zip
ETag: "dbc016a060da18070593b83afff580c9b300f0b6ea4147a7988433e04df246ca"
Strict-Transport-Security: max-age=31536000
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-XSS-Protection: 1; mode=block
X-GitHub-Request-Id: 7300:655ED:461E38:865E35:68FA288B
Accept-Ranges: bytes
Date: Thu, 23 Oct 2025 13:07:25 GMT
Via: 1.1 varnish
X-Served-By: cache-ccu830046-CCU
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1761224845.580552,VS0,VE801
Vary: Authorization,Accept-Encoding
Access-Control-Allow-Origin: *
Cross-Origin-Resource-Policy: cross-origin
X-Fastly-Request-ID: 1d086757f8be43c6c37e4dd99a2ba409b01cc289
Expires: Thu, 23 Oct 2025 13:12:25 GMT
Source-Age: 0

]
[2025-10-23 18:37:25,603: INFO: data_ingestion: File extracted to artifacts\data_ingestion]
[2025-10-23 18:37:25,604: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

X==========x]
[2025-10-23 18:37:25,604: INFO: main: >>>>>> Stage Data Validation Stage started <<<<<<]
[2025-10-23 18:37:25,606: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 18:37:25,607: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 18:37:25,607: INFO: common: created directory at: artifacts]
[2025-10-23 18:37:25,608: INFO: common: created directory at: artifacts/data_validation]
[2025-10-23 18:37:25,608: INFO: main: >>>>>> Stage Data Validation Stage completed <<<<<<

X==========x]
[2025-10-23 18:37:25,609: INFO: main: >>>>>> Stage Data Transformation Stage started <<<<<<]
[2025-10-23 18:37:25,611: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 18:37:25,612: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 18:37:25,613: INFO: common: created directory at: artifacts]
[2025-10-23 18:37:25,613: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-23 18:37:29,233: INFO: main: >>>>>> Stage Data Transformation Stage completed <<<<<<

X==========x]
[2025-10-23 18:37:29,234: INFO: main: >>>>>> Stage Model Trainer Stage started <<<<<<]
[2025-10-23 18:37:29,236: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 18:37:29,238: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 18:37:29,238: INFO: common: created directory at: artifacts]
[2025-10-23 18:37:29,239: INFO: common: created directory at: artifacts/model_trainer]
[2025-10-23 23:09:35,311: INFO: main: >>>>>> Stage Model Trainer Stage completed <<<<<<

X==========x]
[2025-10-23 23:13:01,392: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 23:13:01,397: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 23:13:01,400: INFO: common: created directory at: artifacts]
[2025-10-23 23:13:01,402: INFO: common: created directory at: artifacts/model_evaluation]
[2025-10-23 23:16:51,931: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 23:16:51,936: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 23:16:51,939: INFO: common: created directory at: artifacts]
[2025-10-23 23:16:51,941: INFO: common: created directory at: artifacts/model_evaluation]
[2025-10-23 23:18:22,832: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 23:18:22,835: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 23:18:22,837: INFO: common: created directory at: artifacts]
[2025-10-23 23:18:22,839: INFO: common: created directory at: artifacts/model_evaluation]
[2025-10-23 23:19:15,632: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 23:19:15,636: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 23:19:15,637: INFO: common: created directory at: artifacts]
[2025-10-23 23:19:15,638: INFO: common: created directory at: artifacts/model_evaluation]
[2025-10-23 23:22:55,855: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-23 23:22:55,859: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-23 23:22:55,860: INFO: common: created directory at: artifacts]
[2025-10-23 23:22:55,862: INFO: common: created directory at: artifacts/model_evaluation]
[2025-10-23 23:28:32,209: INFO: rouge_scorer: Using default tokenizer.]
[2025-10-24 00:07:16,949: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-24 00:07:16,954: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-24 00:07:16,955: INFO: common: created directory at: artifacts]
[2025-10-24 00:07:16,957: INFO: common: created directory at: artifacts/model_evaluation]
[2025-10-24 00:08:45,065: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-24 00:08:45,070: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-24 00:08:45,073: INFO: common: created directory at: artifacts]
[2025-10-24 00:08:45,074: INFO: common: created directory at: artifacts/model_evaluation]
[2025-10-24 00:16:13,552: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-24 00:16:13,554: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-24 00:16:13,555: INFO: common: created directory at: artifacts]
[2025-10-24 00:16:13,557: INFO: common: created directory at: artifacts/model_evaluation]
[2025-10-24 00:24:19,091: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-24 00:24:19,095: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-24 00:24:19,097: INFO: common: created directory at: artifacts]
[2025-10-24 00:24:19,098: INFO: common: created directory at: artifacts/model_evaluation]
[2025-10-24 00:24:58,198: INFO: rouge_scorer: Using default tokenizer.]
[2025-10-24 00:26:30,685: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-24 00:26:30,689: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-24 00:26:30,692: INFO: common: created directory at: artifacts]
[2025-10-24 00:26:30,694: INFO: common: created directory at: artifacts/model_evaluation]
[2025-10-24 00:27:07,269: INFO: rouge_scorer: Using default tokenizer.]
[2025-10-24 00:44:42,994: INFO: main: >>>>>> Stage Data Ingestion Stage started <<<<<<]
[2025-10-24 00:44:42,997: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-24 00:44:42,998: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-24 00:44:42,998: INFO: common: created directory at: artifacts]
[2025-10-24 00:44:42,999: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-24 00:44:43,001: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-24 00:44:43,002: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-24 00:44:43,002: INFO: common: created directory at: artifacts]
[2025-10-24 00:44:43,002: INFO: common: created directory at: artifacts/data_ingestion]
[2025-10-24 00:44:43,003: INFO: data_ingestion: File already exists of size: ~ 7718 KB]
[2025-10-24 00:44:43,108: INFO: data_ingestion: File extracted to artifacts\data_ingestion]
[2025-10-24 00:44:43,108: INFO: main: >>>>>> Stage Data Ingestion Stage completed <<<<<<

X==========x]
[2025-10-24 00:44:43,109: INFO: main: >>>>>> Stage Data Validation Stage started <<<<<<]
[2025-10-24 00:44:43,113: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-24 00:44:43,115: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-24 00:44:43,116: INFO: common: created directory at: artifacts]
[2025-10-24 00:44:43,116: INFO: common: created directory at: artifacts/data_validation]
[2025-10-24 00:44:43,119: INFO: main: >>>>>> Stage Data Validation Stage completed <<<<<<

X==========x]
[2025-10-24 00:44:43,120: INFO: main: >>>>>> Stage Data Transformation Stage started <<<<<<]
[2025-10-24 00:44:43,126: INFO: common: yaml file: config\config.yaml loaded successfully]
[2025-10-24 00:44:43,129: INFO: common: yaml file: params.yaml loaded successfully]
[2025-10-24 00:44:43,130: INFO: common: created directory at: artifacts]
[2025-10-24 00:44:43,131: INFO: common: created directory at: artifacts/data_transformation]
[2025-10-24 00:44:44,865: ERROR: main: [Errno 22] Invalid argument: 'D:/Version Control/AI-Text-Summarizer/artifacts/data_transformation/dataset_samsum_pt/train/data-00000-of-00001.arrow']
Traceback (most recent call last):
  File "D:\Version Control\AI-Text-Summarizer\main.py", line 38, in <module>
    data_transformation.main()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\pipeline\stage_03_data_transformation.py", line 15, in main
    data_transformation.convert()
  File "D:\Version Control\AI-Text-Summarizer\src\textSummarizer\components\data_transformation.py", line 25, in convert
    dataset_samsum.save_to_disk(os.path.join(self.config.root_dir, "dataset_samsum_pt"))
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\dataset_dict.py", line 1360, in save_to_disk
    dataset.save_to_disk(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\arrow_dataset.py", line 1624, in save_to_disk
    for job_id, done, content in Dataset._save_to_disk_single(**kwargs):
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\arrow_dataset.py", line 1648, in _save_to_disk_single
    writer = ArrowWriter(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\datasets\arrow_writer.py", line 451, in __init__
    self.stream = self._fs.open(path, "wb")
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\fsspec\spec.py", line 1338, in open
    f = self._open(
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\fsspec\implementations\local.py", line 210, in _open
    return LocalFileOpener(path, mode, fs=self, **kwargs)
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\fsspec\implementations\local.py", line 387, in __init__
    self._open()
  File "C:\Users\aminu\Miniconda3\envs\textS\lib\site-packages\fsspec\implementations\local.py", line 392, in _open
    self.f = open(self.path, mode=self.mode)
OSError: [Errno 22] Invalid argument: 'D:/Version Control/AI-Text-Summarizer/artifacts/data_transformation/dataset_samsum_pt/train/data-00000-of-00001.arrow'
